export const products = [
  {
    image: '/watch.svg',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: '$79.00',
    salePrice: '$68.00',
    rate: '4.9',
    numberOfFeedbacks: 98,
  },
  {
    image: '/watch.svg',
    isDiscount: false,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: '$100.00',
    salePrice: '$90.00',
    rate: '4.8',
    numberOfFeedbacks: 79,
  },
  {
    image: '/watch.svg',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: '$89.00',
    salePrice: '$78.00',
    rate: '4.7',
    numberOfFeedbacks: 101,
  },
  {
    image: '/watch.svg',
    isDiscount: false,
    percentDiscount: 30,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: '$89.00',
    salePrice: '$78.00',
    rate: '4.6',
    numberOfFeedbacks: 20,
  },
  {
    image: '/watch.svg',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: '$79.00',
    salePrice: '$68.00',
    rate: '4.9',
    numberOfFeedbacks: 98,
  },
  {
    image: '/watch.svg',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: '$79.00',
    salePrice: '$68.00',
    rate: '4.9',
    numberOfFeedbacks: 98,
  },
  {
    image: '/watch.svg',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: '$79.00',
    salePrice: '$68.00',
    rate: '4.9',
    numberOfFeedbacks: 98,
  },
  {
    image: '/watch.svg',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: '$79.00',
    salePrice: '$68.00',
    rate: '4.9',
    numberOfFeedbacks: 98,
  },
  {
    image: '/watch.svg',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: '$79.00',
    salePrice: '$68.00',
    rate: '4.9',
    numberOfFeedbacks: 98,
  },
];
