export const products = [
  {
    id: '1',
    image: '/product-detail-1.png',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: 129.99,
    salePrice: 168.99,
    rate: 4.9,
    numberOfFeedbacks: 98,
  },
  {
    id: '2',
    image: '/product-detail-1.png',
    isDiscount: false,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: 100.98,
    rate: 4.8,
    numberOfFeedbacks: 79,
  },
  {
    id: '3',
    image: '/product-detail-1.png',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: 89.0,
    salePrice: 78.0,
    rate: 4.7,
    numberOfFeedbacks: 101,
  },
  {
    id: '4',
    image: '/product-detail-1.png',
    isDiscount: false,
    percentDiscount: 30,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: 89.99,
    salePrice: 78.99,
    rate: 4.6,
    numberOfFeedbacks: 20,
  },
  {
    id: '5',
    image: '/product-detail-1.png',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: 79.0,
    salePrice: 68.0,
    rate: 4.9,
    numberOfFeedbacks: 98,
  },
  {
    id: '6',
    image: '/product-detail-1.png',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: 79.0,
    salePrice: 68.0,
    rate: 4.9,
    numberOfFeedbacks: 98,
  },
  {
    id: '7',
    image: '/product-detail-1.png',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: 79.0,
    salePrice: 68.0,
    rate: 4.9,
    numberOfFeedbacks: 98,
  },
  {
    id: '8',
    image: '/product-detail-1.png',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: 79.0,
    salePrice: 68.0,
    rate: 4.9,
    numberOfFeedbacks: 98,
  },
  {
    id: '9',
    image: '/product-detail-1.png',
    isDiscount: true,
    percentDiscount: 50,
    productName: 'Black Automatic Watch',
    productCategory: 'Accessories',
    price: 79.0,
    salePrice: 68.0,
    rate: 4.9,
    numberOfFeedbacks: 98,
  },
];
